### ISSUE TITLE
Crash after new game start: on_nth_tick(600) : attempt to compare nil with number

### ISSUE THREAD

**Issue by Atlntssplayer** [renoth/factorio-alien-module#87]
Hello

After I started a new game I got this error:

The mod Alien Loot Economy (1.4.2) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event alien-module::on_nth_tick(600)
__alien-module__/control.lua:383: attempt to compare nil with number
stack traceback:
	__alien-module__/control.lua:383: in function <__alien-module__/control.lua:371>

I don't really have the programming knowledge to understand what is happening, but I have a feeling it might have something to do with one or two of the following mods:

Arachnids_enemy_1.0.2
ArachnidsFaction_1.1.4

If I put the following new line in after line 377 in control.lua of alien-module_1.4.2
and force.name ~= "arachnid"
then it doesn't seem to error on new game start but as I mentioned I don't really have the knowledge to actually know what is the good solution.

Other mods I have that have something to do with biters:

ArmouredBiters_1.1.9
Cold_biters_1.2.1
Explosive_biters_2.0.5
Toxic_biters_1.1.5

Thank you

**Comment by renoth** [comment]
Thanks for reporting, i will look into it.

**Comment by renoth** [comment]
Should be fixed in 1.4.3

**Comment by MysterGeOrGe** [comment]
Hello,  i have still a problem link to this error:

The mod Alien Loot Economy (1.4.3) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event alien-module::on_nth_tick(600)
__alien-module__/control.lua:380: attempt to index field 'ignoredalienmodulefactions' (a nil value)
stack traceback:
__alien-module__/control.lua:380: in function <__alien-module__/control.lua:374>

Thanks for the mod, i enjoyed it for many years !

**Comment by renoth** [comment]
Thanks for reporing, does it work with 1.4.4?

**Comment by MysterGeOrGe** [comment]
YES !  thanks a lot !
